### PR TITLE
Add go.mod

### PR DESCRIPTION
**Pull request by mattn**
BTW, We might as well move to GitHub Actions.

### CODE REVIEW

**Comment by mattn** [comment]
Hmm, I may have created this pull-request before the gosum index was created.

**Comment by mattn** [comment]
http://honnef.co/go/lint was gone?

**Comment by itchyny** [comment]
Note honnef.co/go/lint has been moved to honnef.co/go/tools/lint. But I'm not sure where lintutil is moved to.

**Comment by itchyny** [comment]
https://github.com/dominikh/go-tools/commit/9a1fe455724d08fc49829ac1e655fb2a0299d206 moves lintutil to lintcmd.

**Comment by haya14busa** [comment]
Ideally, I should fix the gosum package but I added a workaround for go-get for now. https://github.com/vim-jp/go-vimlparser/pull/51

**Pull request closed without merging**
